[package]
name = "airly_rs"
version = "0.1.0"
authors = ["bartOssh <lenart.consulting@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
reqwest = "0.9.22"
